import{a as h,i as n,S as g}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();async function u(e,o){const s="51719730-f0601b97791df742fe437894d",i="https://pixabay.com/api/",t={key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await h.get(i,{params:t})).data}catch(r){return n.error({title:"Error",message:`Не вдалося отримати зображення: ${r.message}`,position:"topRight",timeout:5e3}),{hits:[],totalHits:0}}}const d=document.querySelector(".gallery"),L=new g(".gallery a");function b(e){return`
    <a href="${e.largeImageURL}" class="gallery__item">
      <img src="${e.webformatURL}" alt="${e.tags}" />
      <div class="stats">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </a>
  `}function f(e){const o=e.map(b).join("");d.insertAdjacentHTML("beforeend",o),L.refresh()}function w(){d.innerHTML=""}function m(){document.querySelector(".loader").classList.add("visible")}function p(){document.querySelector(".loader").classList.remove("visible")}function S(){const e=document.querySelector(".js-loadbtn");e.classList.contains("is-hidden")&&e.classList.remove("is-hidden")}function y(){const e=document.querySelector(".js-loadbtn");e.classList.contains("is-hidden")||e.classList.add("is-hidden")}const v=document.querySelector(".form"),q=document.querySelector(".form-input"),E=document.querySelector(".js-loadbtn");let l="",a=1;v.addEventListener("submit",async e=>{e.preventDefault();const o=q.value.trim();if(!o){n.info({title:"Info",message:"Please enter a search query!",position:"topCenter"});return}l=o,a=1,w(),y(),m();try{const s=await u(l,a);if(s.hits.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}f(s.hits),S()}catch(s){n.error({title:"Error",message:"Something went wrong. Try again later.",position:"topCenter"}),console.error("Fetch error:",s)}finally{p()}});E.addEventListener("click",async()=>{a+=1,m();try{const e=await u(l,a);if(e.hits.length===0){n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"}),y();return}f(e.hits),C()}catch(e){n.error({title:"Error",message:"Failed to load more images.",position:"topCenter"}),console.error("Load more error:",e)}finally{p()}});function C(){const e=document.querySelector(".gallery__item");if(!e)return;const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
